name: Arduino CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        board:
          - arduino:avr:uno
          - esp32:esp32:esp32
          - esp8266:esp8266:nodemcuv2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Configure Board URLs
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Update index
        run: arduino-cli core update-index

      - name: Install cores
        run: |
          arduino-cli core install arduino:avr
          arduino-cli core install esp32:esp32
          arduino-cli core install esp8266:esp8266

      - name: Compile examples
        run: |
          echo "Board: ${{ matrix.board }}"
          for example in $(find examples -name "*.ino"); do

            # Skip ESP32 specific example for non-ESP32 boards
            if [[ "$example" == *ESP32_Custom_I2C_Pins* ]] && [[ "${{ matrix.board }}" != "esp32:esp32:esp32" ]]; then
              echo "Skipping $example (ESP32 only)"
              continue
            fi

            echo "Compiling $example"
            arduino-cli compile --fqbn ${{ matrix.board }} --library . $example
          done
